src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')] // Gestion des created et updated
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(length: 80, nullable: true)]
    private ?string $username = null;

    #[ORM\Column(length: 80, nullable: true)]
    private ?string $fullname = null;

    #[ORM\Column]
    private ?bool $is_major = null;

    #[ORM\Column]
    private ?bool $is_terms = null;

    #[ORM\Column]
    private ?bool $is_gpdr = null;

    #[ORM\OneToOne(mappedBy: 'pro', cascade: ['persist', 'remove'])]
    private ?Detail $detail = null;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    /**
     * @var Collection<int, LoginHistory>
     */
    #[ORM\OneToMany(targetEntity: LoginHistory::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $loginHistories;

    #[ORM\OneToOne(mappedBy: 'client', cascade: ['persist', 'remove'])]
    private ?Subscription $subscription = null;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'user')]
    private Collection $messages;

    /**
     * @var Collection<int, Discussion>
     */
    #[ORM\OneToMany(targetEntity: Discussion::class, mappedBy: 'sender')]
    private Collection $discussions;

    /**
     * Constructeur pour gérer les 
     * attributs non-nullables par défaut
     */
    public function __construct()
    {
        $this->is_major = false;
        $this->is_terms = false;
        $this->is_gpdr = false;
        $this->loginHistories = new ArrayCollection();
        $this->image = "default.png";
        $this->messages = new ArrayCollection();
        $this->discussions = new ArrayCollection();
    }
    
    #[ORM\PrePersist]
    public function setCreatedAtValue()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->updated_at = new \DateTimeImmutable();
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue()
    {
        $this->updated_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(?string $fullname): static
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function isMajor(): ?bool
    {
        return $this->is_major;
    }

    public function setIsMajor(bool $is_major): static
    {
        $this->is_major = $is_major;

        return $this;
    }

    public function isTerms(): ?bool
    {
        return $this->is_terms;
    }

    public function setIsTerms(bool $is_terms): static
    {
        $this->is_terms = $is_terms;

        return $this;
    }

    public function isGpdr(): ?bool
    {
        return $this->is_gpdr;
    }

    public function setIsGpdr(bool $is_gpdr): static
    {
        $this->is_gpdr = $is_gpdr;

        return $this;
    }

    public function getDetail(): ?Detail
    {
        return $this->detail;
    }

    public function setDetail(Detail $detail): static
    {
        // set the owning side of the relation if necessary
        if ($detail->getPro() !== $this) {
            $detail->setPro($this);
        }

        $this->detail = $detail;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function getPathImage(): ?string
    {
        if ($this->image == 'default.png' || $this->image == null) {
            return '/medias/images/users/default.png';
        }
        return '/medias/images/users/' . $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, LoginHistory>
     */
    public function getLoginHistories(): Collection
    {
        return $this->loginHistories;
    }

    public function addLoginHistory(LoginHistory $loginHistory): static
    {
        if (!$this->loginHistories->contains($loginHistory)) {
            $this->loginHistories->add($loginHistory);
            $loginHistory->setUser($this);
        }

        return $this;
    }

    public function removeLoginHistory(LoginHistory $loginHistory): static
    {
        if ($this->loginHistories->removeElement($loginHistory)) {
            // set the owning side to null (unless already changed)
            if ($loginHistory->getUser() === $this) {
                $loginHistory->setUser(null);
            }
        }

        return $this;
    }

    public function isComplete(): bool
    {
        if (!empty($this->username) && !empty($this->fullname)) {
            return true;
        }

        return false;
    }

    public function getSubscription(): ?Subscription
    {
        return $this->subscription;
    }

    public function setSubscription(Subscription $subscription): static
    {
        // set the owning side of the relation if necessary
        if ($subscription->getClient() !== $this) {
            $subscription->setClient($this);
        }

        $this->subscription = $subscription;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setUser($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getUser() === $this) {
                $message->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Discussion>
     */
    public function getDiscussions(): Collection
    {
        return $this->discussions;
    }

    public function addDiscussion(Discussion $discussion): static
    {
        if (!$this->discussions->contains($discussion)) {
            $this->discussions->add($discussion);
            $discussion->setSender($this);
        }

        return $this;
    }

    public function removeDiscussion(Discussion $discussion): static
    {
        if ($this->discussions->removeElement($discussion)) {

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Form\UserFormType;
use App\Service\UploaderService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

final class UserController extends AbstractController
{
    public function __construct(private EntityManagerInterface $em) {}
    #[Route('/profile', name: 'app_profile', methods: ['GET', 'POST'])]
    public function index(
        Request $request, 
        UploaderService $us,
        UserPasswordHasherInterface $passwordHasher
        ): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(UserFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $password = $passwordHasher->isPasswordValid( // isPasswordValid() retourne true ou false
                $user, // Utilisateur actuel
                $form->get('password')->getData() // Récupère le password du formulaire
            );

            if ($password) 
            { // TODO: Vérification de mot de passe
                $image = $form->get('image')->getData(); // Récupère l'image
                if ($image != null) { // Si l'image est téléversée
                    $user->setImage( // Méthode de mutation de l'image
                        $us->uploadFile( // Méthode de téléversement
                            $image, // Image téléversée
                            $user->getImage() // Image actuelle
                            )
                    );
                }

                $this->em->persist($user);
                $this->em->flush();
                
                // Redirection avec flash message
                $this->addFlash('success', 'Votre profil à été mis à jour');
            }
            $this->addFlash('error', 'Une erreur est survenue');

            return $this->redirectToRoute('app_profile');
        }

        if (!$this->getUser()->isVerified()) {
            $this->addFlash('danger', 'Merci de validez votre adresse e-mail.');
        }

        return $this->render('user/index.html.twig', [
            'userForm' => $form,
        ]);
    }

    #[Route('/complete', name: 'app_complete', methods: ['POST'])]
    public function complete(Request $request): Response
    {
        $data = $request->getPayload(); // on récupère les données du formulaire
        if (!empty($data->get('username')) && !empty($data->get('fullname'))) {
            // Enregistrer les données dans la base de données
            $user = $this->getUser(); // Ici on récupère l'utilisateur actuel
            $user
                ->setUsername($data->get('username')) // on met à jour username
                ->setFullname($data->get('fullname')) // on met à jour fullname
                ;
            $this->em->persist($user); // on persiste l'utilisateur
            $this->em->flush(); // on sauvegarde les modifications en base de données
            
            // Redirection avec flash message
            $this->addFlash('success', 'Votre profil est complété');
        } else {
            $this->addFlash('error', 'Vous devez remplir tous les champs');
        }
        return $this->redirectToRoute('app_profile');
    }
}

templates/user/complete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Complétez votre profil{% endblock %}

{% block body %}
<div class="vh-100 center">
    <form action={{ path('app_complete') }} method="post" class="container-xs border rounded p-3">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
        <div class="form-group mb-3">
            <label for="username" class="form-label">Nom d'utilisateur</label>
            <input type="text" class="form-control" id="username" name="username" value="{{ app.user.username ?? '' }}" {{ app.user.username ? 'readonly' : '' }} required minlength="2" maxlength="80">
            <p class="help fst-italic">
                2 caractères minimum, uniquement des lettres, des chiffres et des tirets.
            </p>
        </div>
        <div class="form-group mb-3">
            <label for="fullname" class="form-label">Nom complet</label>
            <input type="text" class="form-control" id="fullname" name="fullname" value="{{ app.user.fullname ?? '' }}" {{ app.user.fullname ? 'readonly' : '' }} required minlength="2" maxlength="80">
        </div>
        <button type="submit" class="btn btn-success">Enregistrer</button>
    </form>
</div>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil - Réglages
{% endblock %}

{% block body %}
{% include 'components/nav.html.twig' %}
	<div class="container pt-5">
		<twig:Salutation/>
		<div class="row m-0">
			<header class="col-md-3 text-center m-0">
				<div class="p-3">
					<img src={{ app.user.pathImage|imagine_filter('square') }} alt={{ app.user.username }} class="img-fluid rounded-circle" width="120">
				</div>
				<div class="card shadow p-3 text-start">
					<p class="border-bottom pb-3">
						{{ ux_icon('mdi:account-circle', { class: 'h-1 me-2 text-secondary' }) }}
						{{ app.user.username }}
						<span class="ms-2 badge text-bg-secondary">{{ app.user.roles[0]|slice(5) }}</span>
					</p>
					<p class="border-bottom pb-3">
						{{ ux_icon('mdi:card-account-details', { class: 'h-1 me-2 text-secondary' }) }}
						{{ app.user.fullname }}
					</p>
					<p class="border-bottom pb-3">
						{{ ux_icon('mdi:email', { class: 'h-1 me-2 text-secondary' }) }}
						{{ app.user.email }}
					</p>
					<p class="pb-3">
						<a href="#" class="text-dark text-decoration-none">
							{{ ux_icon('mdi:pencil', { class: 'h-1 me-2 text-secondary' }) }}
							Ma page de profil public
						</a>
					</p>
					<hr>
					<p class="help text-center">Compte créé il y a
						{{ app.user.createdAt|time_diff }}</p>
				</div>
			</header>
			<section class="col-md-9 p-3 text-decoration-none">
				<div class="row">
					<div class="card shadow p-3 col-md-4">
						{{ form(userForm) }}
							<p class="mt-3 help">Dernière modification il y a
								{{ app.user.updatedAt|time_diff }}</p>
						</div>
						<div class="col-md-8">
							<div class="row">
								<div class="col-md-6">
									<div class="card shadow p-3">
										<div class="card-title fs-5 fw-bold">
											{{ ux_icon('mdi:cog', { class: 'h-1 me-2 text-secondary' }) }}
											Mon abonnement
										</div>
										<div class="card-body">
											{% if app.user.subscription is not null and app.user.subscription.isActive %}
												<p class="mb-3">
													Vous êtes abonné(e) à :
													{{ app.user.subscription.amount }}&euro; /  {{ app.user.subscription.frequency }}
												</p>
											{% else %}
												<p class="mb-3">
													Aucun abonnement actuellement
												</p>
												<form action="{{ path('app_subscription') }}" method="post">
													<input type="hidden" name="csrf_token" value="{{ csrf_token('app_profile') }}">
													<div class="d-flex justify-content-between">
														<select class="btn btn-secondary w-100" name="plan">
															<option value="990">990&euro; /an</option>
															<option value="99">99&euro; /mois</option>
														</select>
														<button class="btn btn-primary" type="submit">S'abonner</button>
													</div>
												</form>
											{% endif %}
										</div>
									</div>
								</div>
								<div class="col-md-6">
									<div class="card shadow p-3">
										<div class="card-title fs-5 fw-bold">
											{{ ux_icon('mdi:book', { class: 'h-1 me-2 text-secondary' }) }}
											Mes landing pages
										</div>
										<div class="card-body">
											<p class="mb-3">
												{{ app.user.detail.landingPages.name ?? 'Aucune landing pages actuellement' }}
											</p>
											<a href="{{ path('lp_add') }}" class="btn btn-primary">Créer une page</a>
										</div>
									</div>
								</div>
							</div>
							<div class="card shadow p-3 mt-4">
								<div class="card-title fs-5 fw-bold">
									{{ ux_icon('mdi:message-text', { class: 'h-1 me-2 text-secondary' }) }}
									Mes derniers échanges
								</div>
								<div class="card-body">
									LES DERNIERS MESSAGES
								</div>
                                <p>{{ ux_icon('mdi:arrow-up', { class: 'h-1 me-2 text-secondary' }) }}</p>
                                <p>
                                
                                </p>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	{% endblock %}